name: wpf-ui-pr-validator

on:
  pull_request:
    branches: [development]
  push:
    branches: [development]

  workflow_dispatch:

jobs:
  matrix_build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          clean: true

      - uses: microsoft/setup-msbuild@v1
        with:
          msbuild-architecture: x64
          vs-prerelease: true

      - uses: nuget/setup-nuget@v1

      - name: Install dependencies
        run: nuget restore src\Wpf.Ui.Gallery\Wpf.Ui.Gallery.csproj

      - name: Build app for release
        run: msbuild src\Wpf.Ui.Gallery\Wpf.Ui.Gallery.csproj -t:rebuild -verbosity:quiet -p:Configuration=Release -p:Platform=x64 -p:RestorePackages=false
