name: wpf-ui-pr-validator

on:
  pull_request:
    branches: [development]
  push:
    branches: [development]

  workflow_dispatch:

jobs:
  matrix_build:
    runs-on: windows-latest
    strategy:
      matrix:
        project:
          - Wpf.Ui
          - Wpf.Ui.Tray
          - Wpf.Ui.ToastNotifications
          - Wpf.Ui.Gallery
    steps:
      - uses: actions/checkout@v3
      - uses: microsoft/setup-msbuild@v1.3
        with:
          msbuild-architecture: x64
      - uses: nuget/setup-nuget@v1
        with:
          nuget-api-key: ${{ secrets.NUGET_API_KEY }}
      - name: Setup .NET Core SDK 7.x
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.x

      - name: Install dependencies
        run: dotnet restore

      - name: Build ${{ matrix.project }}
        run: dotnet build src\${{ matrix.project }}\${{ matrix.project }}.csproj --configuration Release --no-restore
